name: DevOps Challenge Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  challenge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test
        
      - name: Challenge Complete
        run: |
          echo "🎉 Challenge completado por: ${{ github.actor }}"
          echo "⏰ Tiempo: $(date)"